//! Traefik integration — auto-create/delete per-client route config files.
//!
//! When a client connects, we write a Traefik dynamic config file for its subdomain.
//! When it disconnects, we delete the file. Traefik's `file` provider with `watch: true`
//! picks up changes automatically and provisions SSL certs via HTTP-01 challenge.

use crate::config::TraefikConfig;
use std::path::{Path, PathBuf};

/// Sanitize client_id for safe use in filenames and Traefik identifiers.
/// Only allows alphanumeric, hyphens, and underscores. Strips everything else.
fn sanitize_id(client_id: &str) -> String {
    client_id
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == '-' || *c == '_')
        .collect()
}

/// Get the config file path for a client: `{config_dir}/zo-{client_id}.yml`
fn route_file_path(config: &TraefikConfig, client_id: &str) -> PathBuf {
    let safe_id = sanitize_id(client_id);
    Path::new(&config.config_dir).join(format!("zo-{safe_id}.yml"))
}

/// Generate the Traefik dynamic config YAML for a single client route.
fn generate_route_config(
    config: &TraefikConfig,
    client_id: &str,
    domain: &str,
    public_port: u16,
) -> String {
    let safe_id = sanitize_id(client_id);
    let router_name = format!("zo-{safe_id}");
    let service_name = format!("zo-{safe_id}");
    let full_domain = format!("{safe_id}.{domain}");

    format!(
        r#"# Auto-generated by zo-tunnel-server for client '{client_id}'
# This file is managed automatically — do not edit manually.
# It will be removed when the client disconnects.

http:
  routers:
    {router_name}:
      rule: "Host(`{full_domain}`)"
      entryPoints:
        - {entrypoint}
      service: {service_name}
      tls:
        certResolver: {cert_resolver}
  services:
    {service_name}:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:{public_port}"
"#,
        client_id = client_id,
        router_name = router_name,
        full_domain = full_domain,
        entrypoint = config.entrypoint,
        service_name = service_name,
        cert_resolver = config.cert_resolver,
        public_port = public_port,
    )
}

/// Create a Traefik route config file for a newly connected client.
///
/// Creates `{config_dir}/zo-{client_id}.yml` so that Traefik can:
/// 1. Route `{client_id}.{domain}` → zo-tunnel public port
/// 2. Provision an SSL cert via the configured cert resolver
pub fn create_route(
    config: &TraefikConfig,
    client_id: &str,
    domain: &str,
    public_port: u16,
) {
    if !config.enabled {
        return;
    }

    let safe_id = sanitize_id(client_id);
    if safe_id.is_empty() {
        tracing::warn!("Traefik: skipping route for empty/invalid client_id '{}'", client_id);
        return;
    }

    // Ensure config directory exists
    let dir = Path::new(&config.config_dir);
    if let Err(e) = std::fs::create_dir_all(dir) {
        tracing::error!("Traefik: failed to create config dir '{}': {}", config.config_dir, e);
        return;
    }

    let content = generate_route_config(config, client_id, domain, public_port);
    let path = route_file_path(config, client_id);

    match std::fs::write(&path, &content) {
        Ok(_) => {
            tracing::info!(
                "🔀 Traefik route created: {}.{} → {}",
                safe_id, domain, path.display()
            );
        }
        Err(e) => {
            tracing::error!(
                "Traefik: failed to write route file '{}': {}",
                path.display(), e
            );
        }
    }
}

/// Remove the Traefik route config file for a disconnected client.
pub fn remove_route(config: &TraefikConfig, client_id: &str) {
    if !config.enabled {
        return;
    }

    let path = route_file_path(config, client_id);
    if path.exists() {
        match std::fs::remove_file(&path) {
            Ok(_) => {
                tracing::info!("🗑️  Traefik route removed: {}", path.display());
            }
            Err(e) => {
                tracing::error!(
                    "Traefik: failed to remove route file '{}': {}",
                    path.display(), e
                );
            }
        }
    }
}

/// Remove all zo-tunnel managed Traefik route files (called on server shutdown).
pub fn cleanup_all(config: &TraefikConfig) {
    if !config.enabled {
        return;
    }

    let dir = Path::new(&config.config_dir);
    if !dir.exists() {
        return;
    }

    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(e) => {
            tracing::error!("Traefik: failed to read config dir '{}': {}", config.config_dir, e);
            return;
        }
    };

    let mut count = 0;
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if name_str.starts_with("zo-") && name_str.ends_with(".yml") {
            if let Err(e) = std::fs::remove_file(entry.path()) {
                tracing::error!("Traefik: failed to remove '{}': {}", entry.path().display(), e);
            } else {
                count += 1;
            }
        }
    }

    if count > 0 {
        tracing::info!("🧹 Traefik: cleaned up {} route file(s)", count);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sanitize_id() {
        assert_eq!(sanitize_id("my-app"), "my-app");
        assert_eq!(sanitize_id("my_app"), "my_app");
        assert_eq!(sanitize_id("myapp123"), "myapp123");
        assert_eq!(sanitize_id("../../../etc"), "etc");
        assert_eq!(sanitize_id("my app"), "myapp");
        assert_eq!(sanitize_id("my.app"), "myapp");
        assert_eq!(sanitize_id(""), "");
    }

    #[test]
    fn test_route_file_path() {
        let config = TraefikConfig {
            enabled: true,
            config_dir: "/etc/traefik/dynamic".into(),
            entrypoint: "websecure".into(),
            cert_resolver: "letsencrypt".into(),
        };
        let path = route_file_path(&config, "my-api");
        assert_eq!(path, PathBuf::from("/etc/traefik/dynamic/zo-my-api.yml"));
    }

    #[test]
    fn test_route_file_path_sanitizes() {
        let config = TraefikConfig {
            enabled: true,
            config_dir: "/etc/traefik/dynamic".into(),
            entrypoint: "websecure".into(),
            cert_resolver: "letsencrypt".into(),
        };
        let path = route_file_path(&config, "../../etc/passwd");
        assert_eq!(path, PathBuf::from("/etc/traefik/dynamic/zo-etcpasswd.yml"));
    }

    #[test]
    fn test_generate_route_config() {
        let config = TraefikConfig {
            enabled: true,
            config_dir: "/etc/traefik/dynamic".into(),
            entrypoint: "websecure".into(),
            cert_resolver: "letsencrypt".into(),
        };

        let content = generate_route_config(&config, "my-api", "tunnel.example.com", 6210);

        assert!(content.contains("Host(`my-api.tunnel.example.com`)"));
        assert!(content.contains("websecure"));
        assert!(content.contains("letsencrypt"));
        assert!(content.contains("http://127.0.0.1:6210"));
        assert!(content.contains("zo-my-api"));
    }

    #[test]
    fn test_create_and_remove_route() {
        let tmp = std::env::temp_dir().join("zo-traefik-test");
        std::fs::create_dir_all(&tmp).unwrap();

        let config = TraefikConfig {
            enabled: true,
            config_dir: tmp.to_string_lossy().into_owned(),
            entrypoint: "websecure".into(),
            cert_resolver: "letsencrypt".into(),
        };

        // Create route
        create_route(&config, "test-app", "tunnel.example.com", 6210);
        let path = route_file_path(&config, "test-app");
        assert!(path.exists());

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("Host(`test-app.tunnel.example.com`)"));

        // Remove route
        remove_route(&config, "test-app");
        assert!(!path.exists());

        // Cleanup
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn test_cleanup_all() {
        let tmp = std::env::temp_dir().join("zo-traefik-cleanup-test");
        std::fs::create_dir_all(&tmp).unwrap();

        let config = TraefikConfig {
            enabled: true,
            config_dir: tmp.to_string_lossy().into_owned(),
            entrypoint: "websecure".into(),
            cert_resolver: "letsencrypt".into(),
        };

        // Create some routes
        create_route(&config, "app1", "tunnel.example.com", 6210);
        create_route(&config, "app2", "tunnel.example.com", 6210);

        // Also create a non-zo file (should NOT be deleted)
        std::fs::write(tmp.join("other.yml"), "other config").unwrap();

        assert!(route_file_path(&config, "app1").exists());
        assert!(route_file_path(&config, "app2").exists());

        // Cleanup
        cleanup_all(&config);

        assert!(!route_file_path(&config, "app1").exists());
        assert!(!route_file_path(&config, "app2").exists());
        assert!(tmp.join("other.yml").exists()); // preserved

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn test_disabled_config_does_nothing() {
        let config = TraefikConfig {
            enabled: false,
            config_dir: "/nonexistent".into(),
            entrypoint: "websecure".into(),
            cert_resolver: "letsencrypt".into(),
        };

        // Should not panic or error — just silently return
        create_route(&config, "test", "tunnel.example.com", 6210);
        remove_route(&config, "test");
        cleanup_all(&config);
    }
}
